version: "3.2"

services:
  web:
    build: .
    volumes:
      - .:/app
    expose:
      - "8080"
    command: uwsgi --ini myapp.ini

  nginx:
    image: nginx:latest
    volumes:
#      - /data/gandalf/argo:/usr/share/nginx/html
      - ./myapp_nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./static:/app/static
    ports:
      - "8005:8005"
    depends_on:
      - web
