version: "3.2"

services:
  flask:
    build: ./web/
    restart: unless-stopped
    container_name: flask_container
    command: "uwsgi --ini mysite.uwsgi.ini"
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - ./log/uwsgi/:/var/log/uwsgi/

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx_container
#    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/gandalf/argo:/usr/share/nginx/html:ro
      - ./nginx/data/nginx:/etc/nginx/conf.d
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
      - uwsgi_data:/tmp/uwsgi/
      - ./log/nginx/:/var/log/nginx/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - flask

  certbot:
    image: certbot/certbot
    container_name: certbot_container
    restart: unless-stopped
    volumes:
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


volumes:
  uwsgi_data:
