version: "3.2"

services:
  nginx_server:
    image: nginx:latest
    container_name: nginx_container
#    build: .
    ports:
      - "80:80"
    volumes:
      - /data/gandalf/argo:/usr/share/nginx/html
#      - /Users/xiaoqi/PycharmProjects/data/gandalf/argo:/usr/share/nginx/html