# https://www.docker.com/blog/how-to-use-the-official-nginx-docker-image/

FROM nginx:latest

#COPY /data/gandalf/argo/plots /usr/share/nginx/html

EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]